class Pokemon
    attr_accessor :name,
                  :jname,
                  :weight,
                  :height,
                  :national_id,
                  :hp,
                  :attack,
                  :defense,
                  :special_attack,
                  :special_defense,
                  :speed,
                  :type,
                  :ability,
                  :species,
                  :level_moves,
                  :hm_moves,
                  :tm_moves,
                  :tutor_moves,
                  :ev_yield,
                  :female_rate,
                  :generation,
                  :form,
                  :egg_cycles,
                  :dex_description,
                  :evolution_chain
end
